# Generated by Django 4.2.7 on 2023-11-05 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.BooleanField(default=False, verbose_name='cтатус верификации')),
                ('document', models.ImageField(blank=True, null=True, upload_to='', verbose_name='документ подтверждающий личность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
