# Generated by Django 4.2.7 on 2023-11-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'документ', 'verbose_name_plural': 'документы'},
        ),
    ]
